name: hanjan_jlpt_free_version
description: Free version of Hanjan JLPT

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.3.8
  custom_rounded_rectangle_border: ^0.2.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/main_icon.png
    - assets/images/main_title.png

  fonts:
    - family: KosugiMaru
      fonts:
        - asset: assets/fonts/KosugiMaru-Regular.ttf
    - family: S-CoreDream
      fonts:
        - asset: assets/fonts/S-CoreDream-1Thin.ttf
          weight: 100
        - asset: assets/fonts/S-CoreDream-2ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/S-CoreDream-3Light.ttf
          weight: 300
        - asset: assets/fonts/S-CoreDream-4Regular.ttf
          weight: 400
        - asset: assets/fonts/S-CoreDream-5Medium.ttf
          weight: 500
        - asset: assets/fonts/S-CoreDream-6Bold.ttf
          weight: 600
        - asset: assets/fonts/S-CoreDream-7ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/S-CoreDream-8Heavy.ttf
          weight: 800
        - asset: assets/fonts/S-CoreDream-9Black.ttf
          weight: 900